version: "3.9"
services:
  orchestrator:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    image: cruzdinis12/sarif-orchestrator
    volumes:
      - ${ORCHESTRATOR_INPUT_HOST_DIR}:/input:ro
      - ${ORCHESTRATOR_OUTPUT_HOST_DIR}:/output:rw
      - ${CONFIG_HOST_DIR}:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw 
    command:
      - "orchestrator"
      - "--input-dir-host"
      - "${ORCHESTRATOR_INPUT_HOST_DIR}"
      - "--output-dir-host"
      - "${ORCHESTRATOR_OUTPUT_HOST_DIR}"
      - "--config-dir-host"
      - "${CONFIG_HOST_DIR}"
      - "--config"
      - "/config/${ORCHESTRATOR_CONFIG_FILE}"
      - "--keep-images"
  report:
    image: cruzdinis12/sarif-orchestrator
    volumes:
      - ${REPORT_INPUT_HOST_DIR}:/input:ro
      - ${REPORT_OUTPUT_HOST_DIR}:/output:rw
      - ${CONFIG_HOST_DIR}:/config:ro
    command:
      - "report"
      - "--type"
      - "${REPORT_TYPE}"
  upload:
    image: cruzdinis12/sarif-orchestrator
    network_mode: "host"
    volumes:
      - ${UPLOAD_INPUT_HOST_DIR}:/input:ro
      - ${CONFIG_HOST_DIR}:/config:ro
    command:
      - "upload"
      - "--config"
      - "/config/${UPLOAD_CONFIG_FILE}"
