[[runs]]

tool = "hadolint"
option = "scan"
args = ["Security-Pipeline-Testing/Dockerfile"]

[[runs]]

tool = "dockle"
option = "scan"
args = ["bioinformaticsua/catalogue:Test"]
custom_args = "--timeout 600s"

[[runs]]

tool = "trivy"
option = "image"
args = ["bioinformaticsua/catalogue:Test"]
depends_on= ["dockle"]