# [[runs]]

# tool = "hadolint"
# option = "scan"
# args = ["Security-Pipeline-Testing/Dockerfile"]

# [[runs]]

# tool = "flake8"
# option = "scan"
# args = ["Security-Pipeline-Testing/app/app.py"]

# [[runs]]

# tool = "eslint"
# option = "scan"
# args = ["Security-Pipeline-Testing/databases_datatable.js"]

# [[runs]]

# tool = "bandit"
# option = "scan"
# args = ["Security-Pipeline-Testing"]
# custom_args = "-r"

# [[runs]]

# tool = "semgrep"
# option = "scan"
# args = ["Security-Pipeline-Testing"]
# platform = "linux/amd64"

# [[runs]]

# tool = "dependency_check"
# option = "scan"
# args = ["Security-Pipeline-Testing/requirements.txt"]
# platform = "linux/amd64"

# [[runs]]

# tool = "horusec"
# option = "scan"
# args = ["Security-Pipeline-Testing"]

# [[runs]]

# tool = "gitleaks"
# option = "detect"
# args = ["Security-Pipeline-Testing"]
# custom_args = "--exit-code 0"
# depends_on= ["horusec"]

# [[runs]]

# tool = "dockle"
# option = "scan"
# args = ["bioinformaticsua/catalogue:Test"]
# custom_args = "--timeout 600s"
# depends_on= ["trivy"]

# [[runs]]

# tool = "trivy"
# option = "image"
# args = ["bioinformaticsua/catalogue:Test"]
# depends_on= ["gitleaks"]

