build = ""
tag = "latest"
image = "sarif-bandit-latest"
output_volume_docker = ""
input_volume_docker = "/data"
default_option = "scan"

[options]
    
scan = "{custom_args} -f sarif -o {output_place} {0}"