build = ""
tag = "7.4.1"
image = "owasp/dependency-check"
output_volume_docker = "/report"
input_volume_docker = "/src"
default_option = "scan"

[options]
    
scan = "{custom_args} -f SARIF -o {output_place} --scan {0}"