tag = "v8.15.0"
image = "zricethezav/gitleaks"
output_volume_docker = ""
input_volume_docker = "/path"
default_option = "detect"
share_socket = 0
share_network = 0

[options]
    
detect = "detect --source '/path/{0}' -r {output_place} -f sarif {custom_args}"