build = ""
tag = "v2.12.0-debian"
image = "hadolint/hadolint"
output_volume_docker = ""
input_volume_docker = ""
default_option = "scan"

[options]

scan = 'sh -c "hadolint /input/{0} {custom_args} -f sarif | tee -a {output_place}"'