tag = "v2.8.0-beta.1-arm64"
image = "horuszup/horusec-cli"
output_volume_docker = ""
input_volume_docker = ""
default_option = "scan"
share_socket = 1
share_network = 1

[options]

scan = "horusec start -p /input/{0} -P {1} -o sarif -O {output_place} {custom_args}"