tag = "1.5.0"
image = "returntocorp/semgrep"
output_volume_docker = ""
input_volume_docker = "/src"
default_option = "scan"
share_socket = 0
share_network = 0

[options]
    
scan = "semgrep scan --config auto --sarif --output {output_place} {0}"