tag = "2.13.0"
image = "owasp/zap2docker-stable"
output_volume_docker = "/zap/wrk"
input_volume_docker = ""
default_option = "scan"
share_socket = 0
share_network = 1

[options]
    
scan = 'bash -c "export target={0}; ./zap.sh -config rules.domxss.browserid=chrome-headless -cmd -addonupdate; ./zap.sh -cmd -autorun /config/zap.yaml"'