tag = "2.12.0"
image = "owasp/zap2docker-stable"
output_volume_docker = "/zap/wrk"
input_volume_docker = ""
default_option = "scan"

[options]
    
scan = 'bash -c "export target={0}; ./zap.sh -cmd -autorun /config/zap.yaml"'